main/urls.py
from django.urls import path
from .views import *

app_name = 'main'
urlpatterns = [
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index'),
    path('accounts/login/', BBLoginView.as_view(), name='login'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
    path('accounts/password/change/', BBPasswordChangeView.as_view(), name='password_change'),


]

samplesite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class AdvUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True, verbose_name='Активацию прошел?')
    send_messages = models.BooleanField(default=True, verbose_name='Слать оповещения о новых комментариях?')

    class Meta(AbstractUser.Meta):
        pass

main/forms.py
from django import forms
from .models import AdvUser


class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'last_name', 'send_messages')

main/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView

from .models import AdvUser
from .forms import ChangeUserInfoForm


def index(request):
    return render(request, 'main/index.html')

def other_page(request, page):
    try:
        template = get_template('main/'+ page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))

class BBLoginView(LoginView):
    template_name = 'main/login.html'


@login_required
def profile(request):
    return render(request, 'main/profile.html')


class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'


class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = AdvUser
    template_name = 'main/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Личные данные пользователя изменены'

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class BBPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль пользователя изменен'

main/templates/layout/base.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="witdh=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Главная{% endblock %} - Доска объявлений</title>
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
    {% bootstrap_javascript jquery='slim' %}
</head>
<body class="container-fluid">
    <header class="mb-4">
        <h1 class="display-1 text-center">Объявления</h1>
    </header>
    <div class="row">
        <ul class="col nav justify-content-end border">
            <li class="nav-item"><a href="#" class="nav-link">Регистрация</a></li>
            {% if user.is_authenticated %}
            <li class="nav-item dropdown"><a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Профиль</a>
                <div class="dropdown-menu">
                    <a href="{% url 'main:profile' %}" class="dropdown-item">Мои объявления</a>
                    <a href="{% url 'main:profile_change' %}" class="dropdown-item">Изменить личные данные</a>
                    <a href="{% url 'main:password_change' %}" class="dropdown-item">Изменить пароль</a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'main:logout' %}" class="dropdown-item">Выйти</a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">Удалить</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item"><a href="{% url 'main:login' %}" class="nav-link">Вход</a></li>
            {% endif %}
        </ul>
    </div>
    <div class="row">
        <nav class="col-md-auto" nav flex-column border>
            <a href="{% url 'main:index' %}" class="nav-link root">Главная</a>
            <span class="nav-link root font-weight-bold" href="#">Транспорт</span>
            <a href="{% url 'main:other' page='about'%}" class="nav-link root">О сайте</a>
        </nav>
        <section class="col border py-2">
            {% bootstrap_messages %}
            {% block content %}
            {% endblock %}
        </section>
    </div>
    <footer class="mt-3">
        <p class="text-right font-italic">&copy; читатели, 2018г.</p>
    </footer>
</body>
</html>

main/templates/main/about.html
{% extends "layout/base.html" %}

{% block title %}О сайте{% endblock %}

{% block content %}
<h2>О сайте</h2>
<p>Сайт для публикации объявлений о продаже, разбитых на рубрики.</p>
<p>Все права принадлежат читателям книги &quot;Django 2.1&quot;.</p>
{% endblock %}

main/templates/main/change_user_info.html
{% extends "layout/base.html" %}

{% load bootstrap4 %}

{% block title %}Правка личных данных{% endblock %}

{% block content %}
<h2>Правка личных данных ползователя {{ user.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Сохранить' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/index.html
{% extends "layout/base.html" %}

{% block content %}
<h2>Последние 10 объявлений</h2>
{% endblock %}

main/templates/main/login.html
{% extends "layout/base.html" %}

{% load bootstrap4 %}

{% block title %}Вход{% endblock %}

{% block content %}
<h2>Вход</h2>
{% if user.is_authenticated %}
<p>Вы уже выполнили вход.</p>
{% else %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <input type="hidden" name="next" value="{{ next }}">
    {% buttons submit='Войти' %}{% endbuttons %}
</form>
{% endif %}
{% endblock %}

main/templates/main/logout.html
{% extends "layout/base.html" %}

{% block title %}Выход{% endblock %}

{% block content %}
<h2>Выход</h2>
<p>Вы успешно вышли с сайта.</p>
{% endblock %}

main/templates/main/password_change.html
{% extends "layout/base.html" %}

{% load bootstrap4 %}

{% block title %}Смена пароля{% endblock %}

{% block content %}
<h2>Смена пароля пользователя {{ user.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Сменить пароль' %} {% endbuttons %}
</form>
{% endblock %}

main/templates/main/profile.html
{% extends "layout/base.html" %}

{% block title %}Профиль пользователя{% endblock %}

{% block content %}
<h2>Профиль пользователя {{ user.username }}</h2>
{% if user.first_name and user.last_name %}
<p>Здравствуйте, {{ user.first_name }} {{ user.last_name }}!</p>
{% else %}
<p>Здравствуйте!</p>
{% endif %}
<h3>Ваши объявления</h3>
{% endblock %}